const { ethers } = require('ethers');
const fs = require('fs');
const path = require('path');

// Load Contract Artifact (ABI)
// In a real setup, this JSON is generated by Hardhat/Truffle
// For this script, we assume a simple ABI based on MedicalAnchor.sol
const CONTRACT_ABI = [
  "function anchorHash(string memory _metaId, string memory _hashString) public",
  "event ProofAnchored(string indexed metaId, bytes32 indexed dataHash, address indexed hospital, uint256 timestamp)"
];

let provider;
let wallet;
let contract;

async function init() {
    if (contract) return;

    const rpcUrl = process.env.ETH_RPC_URL || 'http://localhost:8545';
    const privateKey = process.env.ETH_PRIVATE_KEY; // Must be set (e.g., from Ganache)
    const contractAddress = process.env.ETH_CONTRACT_ADDRESS;

    if (!privateKey || !contractAddress) {
        throw new Error("ETH_PRIVATE_KEY and ETH_CONTRACT_ADDRESS must be set in .env");
    }

    provider = new ethers.JsonRpcProvider(rpcUrl);
    wallet = new ethers.Wallet(privateKey, provider);
    contract = new ethers.Contract(contractAddress, CONTRACT_ABI, wallet);

    console.log(`[ETHEREUM] Connected to ${rpcUrl}`);
}

async function anchorHash(recordId, dataHash, senderId) {
    await init();

    console.log(`[ETHEREUM] Anchoring Hash for Record: ${recordId}`);
    try {
        // Send Transaction
        const tx = await contract.anchorHash(recordId, dataHash);
        console.log(`[ETHEREUM] Tx Sent: ${tx.hash}. Waiting for confirmation...`);

        const receipt = await tx.wait();
        console.log(`[ETHEREUM] Tx Mined in Block: ${receipt.blockNumber}`);

        return tx.hash;
    } catch (error) {
        console.error(`[ETHEREUM] Error: ${error.message}`);
        throw error;
    }
}

module.exports = { anchorHash };
